image:
  file: .gitpod.Dockerfile
github:
  prebuilds:
    master: true
    branches: true
tasks:
  - init: |
      cabal update
      stack build
    command: |
      stack test
vscode:
  extensions:
    - haskell.haskell