#!/usr/bin/env bash
# SEE: https://github.com/ElvishJerricco/reflex-project-skeleton

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

nix-shell -Q $DIR/default.nix -A shells.ghc --add-root $DIR/dist-newstyle/gc-roots/gc-root --indirect --run "cabal $(printf "%q " "$@")"
