user-message: "WARNING: This stack project is generated."

flags:
    detour-via-sci:
        suppress-failing-tests: true
    detour-via-uom:
        suppress-failing-tests: true
    flight-clip:
        suppress-failing-tests: true
    flight-comp:
        suppress-failing-tests: true
    flight-earth:
        suppress-failing-tests: true
    flight-fsdb:
        suppress-failing-tests: true
    flight-gap-allot:
        suppress-failing-tests: false
    flight-gap-effort:
        suppress-failing-tests: false
    flight-gap-lead:
        suppress-failing-tests: true
    flight-gap-math:
        suppress-failing-tests: false
    flight-gap-stop:
        suppress-failing-tests: false
    flight-gap-valid:
        suppress-failing-tests: false
    flight-gap-weight:
        suppress-failing-tests: true
    flight-gap:
        suppress-failing-tests: true
    flight-igc:
        suppress-failing-tests: true
    flight-kml:
        suppress-failing-tests: true
    flight-mask:
        suppress-failing-tests: true
    flight-task:
        suppress-failing-tests: true
    flight-time:
        suppress-failing-tests: true
    flight-track:
        suppress-failing-tests: true
    flight-units:
        suppress-failing-tests: false
    flight-zone:
        suppress-failing-tests: true
    app-serve:
        suppress-failing-tests: true
    flare-timing:
        suppress-test-parsers: true

resolver: lts-11.22

# We have upgraded 33 packages and have 33 yet to do.
packages:
  - ./lang-haskell/app-serve
  - ./lang-haskell/build
  - ./lang-haskell/clip
  - ./lang-haskell/cmd
  - ./lang-haskell/comp
  - ./lang-haskell/detour-via-sci
  - ./lang-haskell/detour-via-uom
  - ./lang-haskell/earth
  - ./lang-haskell/flare-timing
  - ./lang-haskell/fsdb
  - ./lang-haskell/gap
  - ./lang-haskell/gap-allot
  - ./lang-haskell/gap-effort
  - ./lang-haskell/gap-lead
  - ./lang-haskell/gap-math
  - ./lang-haskell/gap-stop
  - ./lang-haskell/gap-valid
  - ./lang-haskell/gap-weight
  - ./lang-haskell/igc
  - ./lang-haskell/kml
  - ./lang-haskell/latlng
  - ./lang-haskell/lookup
  - ./lang-haskell/mask
  - ./lang-haskell/route
  - ./lang-haskell/scribe
  - ./lang-haskell/siggy-chardust
  - ./lang-haskell/span
  - ./lang-haskell/task
  - ./lang-haskell/tasty-compare
  - ./lang-haskell/time
  - ./lang-haskell/track
  - ./lang-haskell/units
  - ./lang-haskell/zone

# We have 3 source packages:
#   * external 0
#   * internal 0
#   * external forks 0
#   * internal forks 3
extra-deps:
  # Source Packages, internal forks of other repositories.
  # Can we upstream and unfork?
  - git: https://github.com/typechecker/hcoord
    commit: e6f72eeb16c10f29b6d2438cca6b7d3978ea91f9
    subdirs:
      - hcoord
      - hcoord-utm
  - git: https://github.com/typechecker/exact-real
    commit: c4308efc37c53e266fee348a80fdfbabb18822be
  - git: https://github.com/blockscope/uom-plugin
    commit: 7419e73e7fa534cced7ecd3232103f6304bed728
    subdirs:
      - uom-plugin

  # Package versions for published packages either not on Stackage or
  # not matching the version on Stackage for the resolver we use.
  # These package-version extra dependencies are equivalent to cabal constraints.
  - HUnit-1.5.0.0
  - aeson-1.3.1.1
  - checkers-0.5.6
  - doctest-0.15.0
  - facts-0.0.1.0
  - hxt-xpath-9.1.2.2
  - megaparsec-7.0.4
  - memoize-0.8.1
  - parser-combinators-1.0.0
  - servant-py-0.1.1.1
