- arguments:
  - -XDataKinds
  - -XDeriveFunctor
  - -XDeriveGeneric
  - -XDeriveAnyClass
  - -XDerivingStrategies
  - -XDisambiguateRecordFields
  - -XFlexibleContexts
  - -XFlexibleInstances
  - -XGeneralizedNewtypeDeriving
  - -XGADTs
  - -XLambdaCase
  - -XMultiParamTypeClasses
  - -XMultiWayIf
  - -XNamedFieldPuns
  - -XOverloadedStrings
  - -XPackageImports
  - -XParallelListComp
  - -XPartialTypeSignatures
  - -XPatternSynonyms
  - -XQuasiQuotes
  - -XRankNTypes
  - -XRecordWildCards
  - -XScopedTypeVariables
  - -XStandaloneDeriving
  - -XTemplateHaskell
  - -XTypeApplications
  - -XTypeFamilies
  - -XTypeOperators
  - -XTypeSynonymInstances
  - -XTupleSections
  - -XUndecidableInstances
- ignore: {name: Reduce duplication}