# Generated by stackage2nix 0.7.2 from "./stack.yaml"
self: { inherit (self) build-flare-timing detour-via-sci detour-via-uom flight-cmd flight-comp flight-earth flight-fsdb flight-gap flight-igc flight-kml flight-latlng flight-lookup flight-mask flight-route flight-scribe siggy-chardust flight-span flight-task tasty-compare flight-track flight-units flight-zone flare-timing www-flare-timing; }
