module Main (main) where

import Test.DocTest (doctest)

arguments :: [String]
arguments =
    [ "-isrc"
    , "library/Flight/Earth/ZoneShape/Double.hs"
    , "library/Flight/Earth/ZoneShape/Rational.hs"
    , "library/Internal/Ellipsoid/Cylinder/Vincenty/Double.hs"
    , "library/Internal/Ellipsoid/Cylinder/Vincenty/Rational.hs"
    , "library/Internal/Ellipsoid/PointToPoint/Andoyer/Double.hs"
    , "library/Internal/Ellipsoid/PointToPoint/Andoyer/Rational.hs"
    , "library/Internal/Ellipsoid/PointToPoint/Vincenty/Double.hs"
    , "library/Internal/Ellipsoid/PointToPoint/Vincenty/Rational.hs"
    , "library/Internal/Ellipsoid/PointToPoint/Double.hs"
    , "library/Internal/Ellipsoid/PointToPoint/Rational.hs"
    , "library/Flight/Earth/Math.hs"
    , "library/Internal/Flat/Cylinder/Double.hs"
    , "library/Internal/Flat/Projected/Double.hs"
    , "library/Internal/Flat/Projected/Internal.hs"
    , "library/Internal/Flat/PointToPoint/Double.hs"
    , "library/Internal/Sphere/Cylinder/Double.hs"
    , "library/Internal/Sphere/PointToPoint/Double.hs"
    , "library/Internal/CylinderOutline/Double.hs"
    , "library/Internal/CylinderOutline/Rational.hs"
    , "-fplugin=Data.UnitsOfMeasure.Plugin"
    , "-fno-warn-partial-type-signatures"
    , "-XDataKinds"
    , "-XDeriveFunctor"
    , "-XDeriveGeneric"
    , "-XDeriveAnyClass"
    , "-XDerivingStrategies"
    , "-XDisambiguateRecordFields"
    , "-XFlexibleContexts"
    , "-XFlexibleInstances"
    , "-XGeneralizedNewtypeDeriving"
    , "-XGADTs"
    , "-XLambdaCase"
    , "-XMultiParamTypeClasses"
    , "-XMultiWayIf"
    , "-XNamedFieldPuns"
    , "-XOverloadedStrings"
    , "-XPackageImports"
    , "-XParallelListComp"
    , "-XPartialTypeSignatures"
    , "-XPatternSynonyms"
    , "-XQuasiQuotes"
    , "-XRankNTypes"
    , "-XRecordWildCards"
    , "-XScopedTypeVariables"
    , "-XStandaloneDeriving"
    , "-XTemplateHaskell"
    , "-XTypeApplications"
    , "-XTypeFamilies"
    , "-XTypeOperators"
    , "-XTypeSynonymInstances"
    , "-XTupleSections"
    , "-XUndecidableInstances"
    ]

main :: IO ()
main = doctest arguments
