name: cabal

on:
  push:
    branches: [main, ci-cabal]
  pull_request:
    branches: [main]

jobs:
  build:
    name: ghc ${{ matrix.ghc }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cabal: ["3.10"]
        ghc:
          - "8.2"

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - uses: haskell-actions/setup@v2
      name: Setup GHC and cabal-install
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: ${{ matrix.cabal }}

    - uses: actions/cache@v1
      name: cache ~/.cabal/store
      with:
        path: ~/.cabal/store
        key: ${{ runner.os }}-${{ matrix.ghc }}-cabal

    - name: build
      run: |
        cabal update
        cabal build all --enable-tests

    # NOTE: Github actions YAML doesn't support anchors.

    - name: flight-clip:doctest
      run: cabal test flight-clip:doctest --test-show-details=direct --test-option="--color=always"

    - name: flight-comp
      run: cabal test flight-comp --test-show-details=direct --test-option="--color=always"

    - name: flight-comp:doctest
      run: cabal test flight-comp:doctest --test-show-details=direct --test-option="--color=always"

    # Variable not in scope: ensureExt :: FileType -> [Char] -> FilePath
    # - name: flight-comp:comp
    #  run: cabal test flight-comp:comp --test-show-details=direct --test-option="--color=always"
 
    - name: detour-via-sci:doctest
      run: cabal test detour-via-sci:doctest --test-show-details=direct --test-option="--color=always"

    # compile error, Not in scope: 'u'
    # - name: detour-via-uom:doctest
    #   run: cabal test detour-via-uom:doctest --test-show-details=direct --test-option="--color=always"

    # on github runner: Examples: 247  Tried: 212  Errors: 0  Failures: 4
    # on mac locally: Examples: 247  Tried: 247  Errors: 0  Failures: 0
    # - name: flight-earth:doctest
    #  run: cabal test flight-earth:doctest --test-show-details=direct --test-option="--color=always"

    - name: flight-earth:geodesy
      run: cabal test flight-earth:geodesy --test-show-details=direct --test-option="--color=always"

    # 81 out of 222 tests failed
    # - name: flight-earth:forbes
    #  run: cabal test flight-earth:forbes --test-show-details=direct --test-option="--color=always"

    - name: flight-earth:greda
      run: cabal test flight-earth:greda --test-show-details=direct --test-option="--color=always"

    - name: flight-earth:greda-r
      run: cabal test flight-earth:greda-r --test-show-details=direct --test-option="--color=always"

    - name: flight-earth:meridian
      run: cabal test flight-earth:meridian-r --test-show-details=direct --test-option="--color=always"

    - name: flight-earth:published
      run: cabal test flight-earth:published --test-show-details=direct --test-option="--color=always"

    - name: flight-earth:published-r
      run: cabal test flight-earth:published-r --test-show-details=direct --test-option="--color=always"

    # compile error
    # - name: flight-earth:zone
    #   run: cabal test flight-earth:zone --test-show-details=direct --test-option="--color=always"

    # compile error
    # - name: flight-earth:cylinder
    #   run: cabal test flight-earth:cylinder --test-show-details=direct --test-option="--color=always"

    # compile error
    # - name: flight-earth:cylinder-r
    #   run: cabal test flight-earth:cylinder-r --test-show-details=direct --test-option="--color=always"

 #library/Flight/Fsdb/Internal/Parse.hs:25:1: error:
 #Error:     Could not find module ‘Flight.Comp’
 #    Perhaps you meant
 #      Flight.Clip (from flight-clip-1.1.0)
 #      Flight.Zone (from flight-zone-0.1.0)
 #    Use -v to see a list of the files searched for.
 #   |
 #25 | import Flight.Comp (UtcOffset(..))
 #   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 #Test suite doctest: FAIL
    # pases locally but fails on github.
    # - name: flight-fsdb:doctest
    #  run: cabal test flight-fsdb:doctest --test-show-details=direct --test-option="--color=always"

    # 5 failures
    # - name: flight-gap-allot:doctest
    #   run: cabal test flight-gap-allot:doctest --test-show-details=direct --test-option="--color=always"

    - name: flight-gap-effort:doctest
      run: cabal test flight-gap-effort:doctest --test-show-details=direct --test-option="--color=always"

    - name: flight-gap-effort:effort
      run: cabal test flight-gap-effort:effort --test-show-details=direct --test-option="--color=always"

    - name: flight-gap-lead:lead
      run: cabal test flight-gap-lead:lead --test-show-details=direct --test-option="--color=always"

    - name: flight-gap-math:doctest
      run: cabal test flight-gap-math:doctest --test-show-details=direct --test-option="--color=always"

    - name: flight-gap-math:math
      run: cabal test flight-gap-math:math --test-show-details=direct --test-option="--color=always"

    - name: flight-gap-stop:stop
      run: cabal test flight-gap-stop:stop --test-show-details=direct --test-option="--color=always"

    - name: flight-gap-valid:valid
      run: cabal test flight-gap-valid:valid --test-show-details=direct --test-option="--color=always"

    - name: flight-gap-weight:weight
      run: cabal test flight-gap-weight:weight --test-show-details=direct --test-option="--color=always"

# Test suite doctest: RUNNING...
### Failure in library/Flight/Igc/Fix.hs:308: expression `(markJason : _, (fixesJason, _)) = let (Right xs) = parse $(embedStr (readFile fileJason)) in (partition isFix <$> partition isMark xs)'
# expected: 
# but got: 
#          <interactive>:63:59: error:
#              • Exception when trying to run compile-time code:
#                  ./test-suite-doctest/Jason_Kath.20180101-000746.18332.30.igc: openFile: does not exist (No such file or directory)
#                Code: embedStr (readFile fileJason)
#              • In the untyped splice: $(embedStr (readFile fileJason))
    # - name: flight-igc:doctest
    #  run: cabal test flight-igc:doctest --test-show-details=direct --test-option="--color=always"

    - name: flight-kml:doctest
      run: cabal test flight-kml:doctest --test-show-details=direct --test-option="--color=always"

    - name: flight-kml:parse
      run: cabal test flight-kml:parse --test-show-details=direct --test-option="--color=always"

    # 1 failure, ‘tasks’ is not a (visible) field of constructor ‘CompSettings’
    # - name: flight-mask:doctest
    #   run: cabal test flight-mask:doctest --test-show-details=direct --test-option="--color=always"

    - name: siggy-chardust:doctest
      run: cabal test siggy-chardust:doctest --test-show-details=direct --test-option="--color=always"

    - name: siggy-chardust:digits
      run: cabal test siggy-chardust:digits --test-show-details=direct --test-option="--color=always"

    # compile errors
    # - name: flight-task:task
    #   run: cabal test flight-task:task --test-show-details=direct --test-option="--color=always"

    # No longer compiles
    # - name: flight-time:golden
    #   run: cabal test flight-time:golden --test-show-details=direct --test-option="--color=always"

    # 1 failure
    # - name: flight-track:doctest
    #   run: cabal test flight-track:doctest --test-show-details=direct --test-option="--color=always"

    - name: flight-units:doctest
      run: cabal test flight-units:doctest --test-show-details=direct --test-option="--color=always"

    - name: flight-zone
      run: cabal test flight-zone --test-show-details=direct --test-option="--color=always"

    - name: flight-zone:doctest
      run: cabal test flight-zone:doctest --test-show-details=direct --test-option="--color=always"

    - name: flight-zone:serial
      run: cabal test flight-zone:serial --test-show-details=direct --test-option="--color=always"
