name: cabal

on:
  push:
    branches: [ci-cabal]
  pull_request:
    branches: [main]

jobs:
  build:
    name: ghc ${{ matrix.ghc }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cabal: ["3.0"]
        ghc:
          - "8.2.2"

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - uses: haskell/actions/setup@v1
      name: Setup GHC and cabal-install
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: ${{ matrix.cabal }}

    - uses: actions/cache@v1
      name: cache ~/.cabal/store
      with:
        path: ~/.cabal/store
        key: ${{ runner.os }}-${{ matrix.ghc }}-cabal

    - name: build
      run: |
        cabal update
        cabal build all --enable-tests

    # NOTE: Github actions YAML doesn't support anchors.

    - name: flight-clip:hlint
      run: cabal test flight-clip:hlint --test-show-details=direct --test-option="--color=always"

    - name: flight-clip:doctest
      run: cabal test flight-clip:hlint --test-show-details=direct --test-option="--color=always"

    - name: flight-cmd:hlint
      run: cabal test flight-cmd:hlint --test-show-details=direct --test-option="--color=always"

    # 46 hints
    # - name: flight-comp
    #   run: cabal test flight-comp --test-show-details=direct --test-option="--color=always"

    - name: flight-comp:doctest
      run: cabal test flight-comp:doctest --test-show-details=direct --test-option="--color=always"

    # Variable not in scope: ensureExt :: FileType -> [Char] -> FilePath
    # - name: flight-comp:comp
    #  run: cabal test flight-comp:comp --test-show-details=direct --test-option="--color=always"
 
    - name: detour-via-sci:hlint
      run: cabal test detour-via-sci:hlint --test-show-details=direct --test-option="--color=always"

### Failure in library/Data/Via/Scientific.hs:81: expression `fromSci x'
# expected: 4043636029064415 % 36028797018963968
# but got: 0.1122334455667788
    # - name: detour-via-sci:doctest
    #   run: cabal test detour-via-sci:doctest --test-show-details=direct --test-option="--color=always"

    # - name: detour-via-uom
    #   run: cabal test detour-via-uom --test-show-details=direct --test-option="--color=always"

    - name: flight-earth
      run: cabal test flight-earth --test-show-details=direct --test-option="--color=always"

    # 14 hints
    # - name: flight-fsdb:hlint
    #   run: cabal test flight-fsdb:hlint --test-show-details=direct --test-option="--color=always"

    - name: flight-fsdb:doctest
      run: cabal test flight-fsdb:doctest --test-show-details=direct --test-option="--color=always"

    # - name: flight-gap-allot
    #   run: cabal test flight-gap-allot --test-show-details=direct --test-option="--color=always"

    # 11 hints
    # - name: flight-gap-effort:hlint
    #   run: cabal test flight-gap-effort:hlint --test-show-details=direct --test-option="--color=always"

    - name: flight-gap-effort:doctest
      run: cabal test flight-gap-effort:doctest --test-show-details=direct --test-option="--color=always"

    - name: flight-gap-effort:effort
      run: cabal test flight-gap-effort:effort --test-show-details=direct --test-option="--color=always"

    - name: flight-gap-lead:hlint
      run: cabal test flight-gap-lead:hlint --test-show-details=direct --test-option="--color=always"

    - name: flight-gap-lead:lead
      run: cabal test flight-gap-lead:lead --test-show-details=direct --test-option="--color=always"

    # - name: flight-gap-math
    #  run: cabal test flight-gap-math --test-show-details=direct --test-option="--color=always"

    - name: flight-gap-stop:hlint
      run: cabal test flight-gap-stop:hlint --test-show-details=direct --test-option="--color=always"

    - name: flight-gap-stop:stop
      run: cabal test flight-gap-stop:stop --test-show-details=direct --test-option="--color=always"

    - name: flight-gap-valid
      run: cabal test flight-gap-valid --test-show-details=direct --test-option="--color=always"

    - name: flight-gap-weight
      run: cabal test flight-gap-weight --test-show-details=direct --test-option="--color=always"

    # 8 hints
    # - name: flight-igc:hlint
    #  run: cabal test flight-igc:hlint --test-show-details=direct --test-option="--color=always"

    # - name: flight-igc:doctest
    #  run: cabal test flight-igc:doctest --test-show-details=direct --test-option="--color=always"
# Test suite doctest: RUNNING...
### Failure in library/Flight/Igc/Fix.hs:308: expression `(markJason : _, (fixesJason, _)) = let (Right xs) = parse $(embedStr (readFile fileJason)) in (partition isFix <$> partition isMark xs)'
# expected: 
# but got: 
#          <interactive>:63:59: error:
#              • Exception when trying to run compile-time code:
#                  ./test-suite-doctest/Jason_Kath.20180101-000746.18332.30.igc: openFile: does not exist (No such file or directory)
#                Code: embedStr (readFile fileJason)
#              • In the untyped splice: $(embedStr (readFile fileJason))

    - name: flight-kml:hlint
      run: cabal test flight-kml:hlint --test-show-details=direct --test-option="--color=always"

    - name: flight-kml:doctest
      run: cabal test flight-kml:doctest --test-show-details=direct --test-option="--color=always"

    - name: flight-kml:parse
      run: cabal test flight-kml:parse --test-show-details=direct --test-option="--color=always"

    - name: flight-latlng:hlint
      run: cabal test flight-latlng:hlint --test-show-details=direct --test-option="--color=always"

    - name: flight-lookup:hlint
      run: cabal test flight-lookup:hlint --test-show-details=direct --test-option="--color=always"

    # - name: flight-mask
    #   run: cabal test flight-mask --test-show-details=direct --test-option="--color=always"

    - name: flight-route
      run: cabal test flight-route --test-show-details=direct --test-option="--color=always"

    - name: flight-scribe:hlint
      run: cabal test flight-scribe:hlint --test-show-details=direct --test-option="--color=always"

    - name: siggy-chardust:hlint
      run: cabal test siggy-chardust:hlint --test-show-details=direct --test-option="--color=always"

    - name: siggy-chardust:doctest
      run: cabal test siggy-chardust:doctest --test-show-details=direct --test-option="--color=always"

    - name: siggy-chardust:digits
      run: cabal test siggy-chardust:digits --test-show-details=direct --test-option="--color=always"

    - name: flight-span:hlint
      run: cabal test flight-span:hlint --test-show-details=direct --test-option="--color=always"

    # - name: flight-task
    #   run: cabal test flight-task --test-show-details=direct --test-option="--color=always"

    - name: flight-time:hlint
      run: cabal test flight-time:hlint --test-show-details=direct --test-option="--color=always"

    # No longer compiles
    # - name: flight-time:golden
    #   run: cabal test flight-time:golden --test-show-details=direct --test-option="--color=always"

    # - name: flight-track
    #   run: cabal test flight-track --test-show-details=direct --test-option="--color=always"

    - name: flight-units:hlint
      run: cabal test flight-units:hlint --test-show-details=direct --test-option="--color=always"

    - name: flight-units:doctest
      run: cabal test flight-units:doctest --test-show-details=direct --test-option="--color=always"

    # 41 hints
    # - name: flight-zone
    #   run: cabal test flight-zone --test-show-details=direct --test-option="--color=always"

    - name: flight-zone:doctest
      run: cabal test flight-zone:doctest --test-show-details=direct --test-option="--color=always"

    # ghc: could not execute: tasty-discover
    # - name: flight-zone:serial
    #   run: cabal test flight-zone:serial --test-show-details=direct --test-option="--color=always"
