name: cabal-ghc-9.2

on:
  push:
    branches: [ci-cabal, wip/ghc-9.2-minimal]
  pull_request:
    branches: [master]

jobs:
  build:
    name: ghc ${{ matrix.ghc }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cabal: ["3.6"]
        ghc:
          - "9.2.1"

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: init submodule uom-plugin/ghc-corroborate
      run: |
        cd lang-haskell/uom-plugin
        git submodule update --init --recursive

    - uses: haskell/actions/setup@v1
      name: Setup GHC and cabal-install
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: ${{ matrix.cabal }}

    - uses: actions/cache@v1
      name: cache ~/.cabal/store
      with:
        path: ~/.cabal/store
        key: ${{ runner.os }}-${{ matrix.ghc }}-cabal

    - name: build
      run: |
        cabal v2-update
        cabal v2-build all:exes --project=cabal-ghc-9.2.project