name: hlint

on:
  push:
    branches: [main, ci-hlint]
  pull_request:
    branches: [main]

jobs:
  build:
    name: hlint-3.5
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - uses: haskell-actions/hlint-setup@v2
      name: Set up HLint
      with:
        version: "3.5"

    - uses: haskell-actions/hlint-run@v2
      name: hlint
      with:
        path: '["."]'
        fail-on: suggestion
