name: pier

on:
  push:
    branches: [main, ci-pier]
  pull_request:
    branches: [main]

jobs:
  build:
    name: ghc ${{ matrix.ghc }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cabal:
          - "3.2"
        ghc:
          - "8.2.2"

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - uses: haskell/actions/setup@v1
      name: setup GHC and cabal-install
      with:
        enable-stack: true
        stack-version: 'latest'
        ghc-version: ${{ matrix.ghc }}
        cabal-version: ${{ matrix.cabal }}

    # SEE: https://github.com/actions/cache/blob/master/examples.md#haskell---cabal
    - uses: actions/cache@v1
      name: cache ~/.stack
      with:
        path: ~/.stack
        key: ${{ runner.os }}-${{ matrix.ghc }}-stack

    - uses: actions/cache@v1
      name: cache .stack-work
      with:
        path: .stack-work
        key: ${{ runner.os }}-${{ matrix.ghc }}-stack-work

    - uses: actions/cache@v1
      name: cache ~/.pier/artifact
      with:
        path: ~/.pier/artifact
        key: ${{ runner.os }}-${{ matrix.ghc }}-shared-pier-artifact

    - uses: actions/cache@v1
      name: cache _pier/artifact
      with:
        path: _pier/artifact
        key: ${{ runner.os }}-${{ matrix.ghc }}-pier-artifact

    - uses: actions/cache@v1
      name: cache-pier-exe
      with:
        path: ~/.local/bin/pier
        key: ${{ runner.os }}-${{ matrix.ghc }}-pier-exe

    - name: install pier
      if: steps.cache-pier-exe.outputs.cache-hit != 'true'
      run: stack install pier --stack-yaml=lang-haskell/stack-pier.yaml

    #- name: flight-clip
       #run: ~/.local/bin/pier test flight-clip

    #- name: flight-cmd
       #run: ~/.local/bin/pier test flight-cmd

    #- name: flight-comp
      #run: ~/.local/bin/pier test flight-comp:test:comp

    #- name: detour-via-sci
      #run: ~/.local/bin/pier test detour-via-sci

    #- name: detour-via-uom
      #run: ~/.local/bin/pier test detour-via-uom

# Build instead of test flight-earth.
# Error when running Shake build system:
# * Test suites from flight-earth
# * Library doctest
# * Library ghc-paths
# * Command: ghc-paths-0.1.0.9: building library

# _pier/artifact/aSAglvFGrs2_ie9NyRDZNIwAaImwZ2zi7zD1npAcXTI/package/raw/ghc-paths-0.1.0.9/GHC/Paths.hs:9:11: error:
#     Data constructor not in scope: GHC_PATHS_LIBDIR :: FilePath
#   |
# 9 | libdir  = GHC_PATHS_LIBDIR
#   |           ^^^^^^^^^^^^^^^^

# _pier/artifact/aSAglvFGrs2_ie9NyRDZNIwAaImwZ2zi7zD1npAcXTI/package/raw/ghc-paths-0.1.0.9/GHC/Paths.hs:10:11: error:
#     Data constructor not in scope: GHC_PATHS_DOCDIR :: FilePath
#    |
# 10 | docdir  = GHC_PATHS_DOCDIR
#    |           ^^^^^^^^^^^^^^^^

# _pier/artifact/aSAglvFGrs2_ie9NyRDZNIwAaImwZ2zi7zD1npAcXTI/package/raw/ghc-paths-0.1.0.9/GHC/Paths.hs:12:11: error:
#     Data constructor not in scope: GHC_PATHS_GHC :: FilePath
#    |
# 12 | ghc     = GHC_PATHS_GHC
#    |           ^^^^^^^^^^^^^

# _pier/artifact/aSAglvFGrs2_ie9NyRDZNIwAaImwZ2zi7zD1npAcXTI/package/raw/ghc-paths-0.1.0.9/GHC/Paths.hs:13:11: error:
#     Data constructor not in scope: GHC_PATHS_GHC_PKG :: FilePath
#    |
# 13 | ghc_pkg = GHC_PATHS_GHC_PKG
#    |           ^^^^^^^^^^^^^^^^^
    - name: flight-earth
      run: ~/.local/bin/pier build flight-earth

    #- name: flight-fsdb
      #run: ~/.local/bin/pier test flight-fsdb

    #- name: flight-gap-allot
      #run: ~/.local/bin/pier test flight-gap-allot

    - name: flight-gap-effort
      run: ~/.local/bin/pier test flight-gap-effort:test:effort

    - name: flight-gap-lead
      run: ~/.local/bin/pier test flight-gap-lead:test:lead

    - name: flight-gap-math
      run: ~/.local/bin/pier test flight-gap-math:test:math

    - name: flight-gap-stop
      run: ~/.local/bin/pier test flight-gap-stop:test:stop

    - name: flight-gap-valid
      run: ~/.local/bin/pier test flight-gap-valid:test:valid

    - name: flight-gap-weight
      run: ~/.local/bin/pier test flight-gap-weight:test:weight

    #- name: flight-igc
      #run: ~/.local/bin/pier test flight-igc

    - name: flight-kml
      run: ~/.local/bin/pier test flight-kml:test:parse

    #- name: flight-latlng
      #run: ~/.local/bin/pier test flight-latlng

    #- name: flight-lookup
      #run: ~/.local/bin/pier test flight-lookup

    #- name: flight-mask
      #run: ~/.local/bin/pier test flight-mask

    #- name: flight-route
      #run: ~/.local/bin/pier test flight-route

    #- name: flight-scribe
      #run: ~/.local/bin/pier test flight-scribe

    - name: siggy-chardust
      run: ~/.local/bin/pier test siggy-chardust:test:digits

    #- name: flight-span
      #run: ~/.local/bin/pier test flight-span

    #- name: flight-task
      #run: ~/.local/bin/pier test flight-task:test:task

    #- name: flight-time
      #run: ~/.local/bin/pier test flight-time

    #- name: flight-track
      #run: ~/.local/bin/pier test flight-track

    #- name: flight-units
      #  run: ~/.local/bin/pier test flight-units

    # NOTE: Test using tasty-discover fails.
    # Error when running Shake build system:
    # * TestSuite serial from flight-zone
    # * Command: flight-zone-0.1.0: building test-suite serial
    # ghc: could not execute: tasty-discover
    #- name: flight-zone
      #run: ~/.local/bin/pier test flight-zone:test:serial
