name: pier

on:
  push:
    branches: [ci-pier]
  pull_request:
    branches: [main]

jobs:
  build:
    name: ghc ${{ matrix.ghc }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cabal:
          - "3.2"
        ghc:
          - "8.2.2"

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    # SEE: # https://github.com/actions/virtual-environments/blob/master/images/linux/Ubuntu1804-README.md
    # NOTE: The advice is to use latest as the stack version but the only one
    # pre-installed is 2.1. Here's the warning from when I'd used latest as the
    # version.
    #
    # stack 2.3.1 was not found in the cache. It will be downloaded.  If this
    # is unexpected, please check if version 2.3.1 is pre-installed.  The list
    # of pre-installed versions is available here:
    # https://help.github.com/en/actions/reference/software-installed-on-github-hosted-runners
    # The above list follows a common haskell convention that the latest
    # release of stack is commonly supported.  If the list is outdated, please
    # file an issue here: https://github.com/actions/virtual-environments by
    # using the appropriate tool request template:
    # https://github.com/actions/virtual-environments/issues/new/choose
    - uses: actions/setup-haskell@v1.1
      name: setup GHC and cabal-install
      with:
        enable-stack: true
        stack-version: 2.1
        ghc-version: ${{ matrix.ghc }}
        cabal-version: ${{ matrix.cabal }}

    # SEE: https://github.com/actions/cache/blob/master/examples.md#haskell---cabal
    - uses: actions/cache@v1
      name: cache ~/.stack
      with:
        path: ~/.stack
        key: ${{ runner.os }}-${{ matrix.ghc }}-stack

    - uses: actions/cache@v1
      name: cache .stack-work
      with:
        path: .stack-work
        key: ${{ runner.os }}-${{ matrix.ghc }}-stack-work

    - uses: actions/cache@v1
      name: cache ~/.pier/artifact
      with:
        path: ~/.pier/artifact
        key: ${{ runner.os }}-${{ matrix.ghc }}-shared-pier-artifact

    - uses: actions/cache@v1
      name: cache _pier/artifact
      with:
        path: _pier/artifact
        key: ${{ runner.os }}-${{ matrix.ghc }}-pier-artifact

    - uses: actions/cache@v1
      name: cache-pier-exe
      with:
        path: ~/.local/bin/pier
        key: ${{ runner.os }}-${{ matrix.ghc }}-pier-exe

    - name: install pier
      if: steps.cache-pier-exe.outputs.cache-hit != 'true'
      run: stack install pier --stack-yaml=lang-haskell/stack-pier.yaml

    #- name: flight-clip
       #run: ~/.local/bin/pier test flight-clip

    #- name: flight-cmd
       #run: ~/.local/bin/pier test flight-cmd

    #- name: flight-comp
      #run: ~/.local/bin/pier test flight-comp:test:comp

    #- name: detour-via-sci
      #run: ~/.local/bin/pier test detour-via-sci

    #- name: detour-via-uom
      #run: ~/.local/bin/pier test detour-via-uom

    - name: flight-earth
      run: ~/.local/bin/pier test flight-earth

    #- name: flight-fsdb
      #run: ~/.local/bin/pier test flight-fsdb

    #- name: flight-gap-allot
      #run: ~/.local/bin/pier test flight-gap-allot

    - name: flight-gap-effort
      run: ~/.local/bin/pier test flight-gap-effort:test:effort

    - name: flight-gap-lead
      run: ~/.local/bin/pier test flight-gap-lead:test:lead

    - name: flight-gap-math
      run: ~/.local/bin/pier test flight-gap-math:test:math

    - name: flight-gap-stop
      run: ~/.local/bin/pier test flight-gap-stop:test:stop

    - name: flight-gap-valid
      run: ~/.local/bin/pier test flight-gap-valid:test:valid

    - name: flight-gap-weight
      run: ~/.local/bin/pier test flight-gap-weight:test:weight

    #- name: flight-igc
      #run: ~/.local/bin/pier test flight-igc

    - name: flight-kml
      run: ~/.local/bin/pier test flight-kml:test:parse

    #- name: flight-latlng
      #run: ~/.local/bin/pier test flight-latlng

    #- name: flight-lookup
      #run: ~/.local/bin/pier test flight-lookup

    #- name: flight-mask
      #run: ~/.local/bin/pier test flight-mask

    #- name: flight-route
      #run: ~/.local/bin/pier test flight-route

    #- name: flight-scribe
      #run: ~/.local/bin/pier test flight-scribe

    - name: siggy-chardust
      run: ~/.local/bin/pier test siggy-chardust:test:digits

    #- name: flight-span
      #run: ~/.local/bin/pier test flight-span

    #- name: flight-task
      #run: ~/.local/bin/pier test flight-task:test:task

    #- name: flight-time
      #run: ~/.local/bin/pier test flight-time

    #- name: flight-track
      #run: ~/.local/bin/pier test flight-track

    #- name: flight-units
      #  run: ~/.local/bin/pier test flight-units

    # NOTE: Test using tasty-discover fails.
    # Error when running Shake build system:
    # * TestSuite serial from flight-zone
    # * Command: flight-zone-0.1.0: building test-suite serial
    # ghc: could not execute: tasty-discover
    #- name: flight-zone
      #run: ~/.local/bin/pier test flight-zone:test:serial
