name: stack

on:
  push:
    branches: [main, ci-stack]
  pull_request:
    branches: [main]

jobs:
  build:
    name: ghc ${{ matrix.ghc }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cabal: ["3.0"]
        ghc:
          - "8.2.2"

    steps:
    - uses: mstksg/get-package@v1
      name: Install OS Packages
      with:
        apt-get: libgmp-dev

    - uses: actions/checkout@v3
      with:
        submodules: true

    - uses: haskell-actions/setup@v2
      name: Setup stack and cabal-install
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: ${{ matrix.cabal }}
        enable-stack: true

    - name: Cache Key
      id: cache_key
      run: echo ::set-output name=key::$(md5sum lang-haskell/stack.yaml | awk '{print $1}')

    - uses: actions/cache@v1
      name: Cache ~/.stack
      id: cache
      with:
        path: ~/.stack
        key: ${{ matrix.os }}-${{ steps.cache_key.outputs.key }}

    # - name: build tests
    #   run: stack test --no-run-tests --no-terminal

    - name: flight-clip:doctest
      run: stack test flight-clip:doctest --no-terminal --test-arguments "--color=always"

    - name: flight-comp:doctest
      run: stack test flight-comp:doctest --no-terminal --test-arguments "--color=always"

    # Variable not in scope: ensureExt :: FileType -> [Char] -> FilePath
    # - name: flight-comp:comp
    #   run: stack test flight-comp:comp --no-terminal --test-arguments "--color=always"

### Failure in library/Data/Via/Scientific.hs:81: expression `fromSci x'
# expected: 4043636029064415 % 36028797018963968
# but got: 0.1122334455667788
    # - name: detour-via-sci:doctest
    #   run: stack test detour-via-sci:doctest --no-terminal --test-arguments "--color=always"

    # compile error, Not in scope: 'u'
    # - name: detour-via-uom:doctest
    #   run: stack test detour-via-uom:doctest --no-terminal --test-arguments "--color=always"

    # on github runner: Examples: 247  Tried: 212  Errors: 0  Failures: 4
    # on mac locally: Examples: 247  Tried: 247  Errors: 0  Failures: 0
    # - name: flight-earth:doctest
    #   run: stack test flight-earth:doctest --no-terminal --test-arguments "--color=always"

    - name: flight-earth:geodesy
      run: stack test flight-earth:geodesy --no-terminal --test-arguments "--color=always"

    # 81 out of 222 tests failed
    # - name: flight-earth:forbes
    #   run: stack test flight-earth:forbes --no-terminal --test-arguments "--color=always"

    - name: flight-earth:greda
      run: stack test flight-earth:greda --no-terminal --test-arguments "--color=always"

    - name: flight-earth:greda-r
      run: stack test flight-earth:greda-r --no-terminal --test-arguments "--color=always"

    - name: flight-earth:meridian
      run: stack test flight-earth:meridian --no-terminal --test-arguments "--color=always"

    - name: flight-earth:meridian-r
      run: stack test flight-earth:meridian-r --no-terminal --test-arguments "--color=always"

    - name: flight-earth:published
      run: stack test flight-earth:published --no-terminal --test-arguments "--color=always"

    - name: flight-earth:published-r
      run: stack test flight-earth:published-r --no-terminal --test-arguments "--color=always"

    # compile error
    # - name: flight-earth:zone
    #   run: stack test flight-earth:zone --no-terminal --test-arguments "--color=always"

    # compile error
    # - name: flight-earth:cylinder
    #  run: stack test flight-earth:cylinder --no-terminal --test-arguments "--color=always"

    # compile error
    # - name: flight-earth:cylinder-r
    #  run: stack test flight-earth:cylinder-r --no-terminal --test-arguments "--color=always"

    - name: flight-fsdb:doctest
      run: stack test flight-fsdb:doctest --no-terminal --test-arguments "--color=always"

    # 5 failures
    # - name: flight-gap-allot:doctest
    #   run: stack test flight-gap-allot:doctest --no-terminal --test-arguments "--color=always"

    - name: flight-gap-effort:doctest
      run: stack test flight-gap-effort:doctest --no-terminal --test-arguments "--color=always"

    - name: flight-gap-effort:effort
      run: stack test flight-gap-effort:effort --no-terminal --test-arguments "--color=always"

    - name: flight-gap-lead:lead
      run: stack test flight-gap-lead:lead --no-terminal --test-arguments "--color=always"

    - name: flight-gap-math:doctest
      run: stack test flight-gap-math:doctest --no-terminal --test-arguments "--color=always"

    - name: flight-gap-math:math
      run: stack test flight-gap-math:math --no-terminal --test-arguments "--color=always"

    - name: flight-gap-stop:stop
      run: stack test flight-gap-stop:stop --no-terminal --test-arguments "--color=always"

    - name: flight-gap-valid:valid
      run: stack test flight-gap-valid:valid --no-terminal --test-arguments "--color=always"

    - name: flight-gap-weight:weight
      run: stack test flight-gap-weight:weight --no-terminal --test-arguments "--color=always"

 #flight-igc > test (suite: doctest, args: --color=always)
 #
 #### Failure in library/Flight/Igc/Fix.hs:308: expression `(markJason : _, (fixesJason, _)) = let (Right xs) = parse $(embedStr (readFile fileJason)) in (partition isFix <$> partition isMark xs)'
 #expected: 
 # but got: 
 #          <interactive>:63:59: error:
 #              • Exception when trying to run compile-time code:
 #                  ./test-suite-doctest/Jason_Kath.20180101-000746.18332.30.igc: openFile: does not exist (No such file or directory)
 #                Code: embedStr (readFile fileJason)
 #              • In the untyped splice: $(embedStr (readFile fileJason))
 #
 #Examples: 110  Tried: 71  Errors: 0  Failures: 1
 #
 #flight-igc > Test suite doctest failed
    # - name: flight-igc:doctest
    #  run: stack test flight-igc:doctest --no-terminal --test-arguments "--color=always"

    - name: flight-kml:doctest
      run: stack test flight-kml:doctest --no-terminal --test-arguments "--color=always"

    - name: flight-kml:parse
      run: stack test flight-kml:parse --no-terminal --test-arguments "--color=always"

    # 1 failure, ‘tasks’ is not a (visible) field of constructor ‘CompSettings’
    # - name: flight-mask:doctest
    #   run: stack test flight-mask:doctest --no-terminal --test-arguments "--color=always"

    - name: siggy-chardust:doctest
      run: stack test siggy-chardust:doctest --no-terminal --test-arguments "--color=always"

    - name: siggy-chardust:digits
      run: stack test siggy-chardust:digits --no-terminal --test-arguments "--color=always"

    # compile errors
    # - name: flight-task:task
    #  run: stack test flight-task:task --no-terminal --test-arguments "--color=always"

    # No longer compiles
    # - name: flight-time:golden
    #   run: stack test flight-time:golden --no-terminal --test-arguments "--color=always"

    # 1 failure
    # - name: flight-track:doctest
    #   run: stack test flight-track:doctest --no-terminal --test-arguments "--color=always"

    - name: flight-units:doctest
      run: stack test flight-units:doctest --no-terminal --test-arguments "--color=always"

    - name: flight-zone:doctest
      run: stack test flight-zone:doctest --no-terminal --test-arguments "--color=always"

    - name: flight-zone:serial
      run: stack test flight-zone:serial --no-terminal --test-arguments "--color=always"
